[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sleeperservice"
version = "v0.0.1"
authors = [
  {name="BuongiornoTexas"},
]
description = "Windows utility to override power requests blocking sleep/hibernate."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pywin32"
]

[project.urls]
"Homepage" = "https://github.com/BuongiornoTexas/sleeperservice"
"Bug Tracker" = "https://github.com/BuongiornoTexas/sleeperservice/issues"